[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[dev]
  command = "bun run dev"
  port = 5173
  framework = "vite"

[images]
  remote_images = [
    "https://images.unsplash.com/.*"
  ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
